
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  bull-board:
    image: ghcr.io/opes04/bull-board-image:latest
    container_name: bull-board
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3001:3000"
    depends_on:
      - redis

  express-app:
    build: .
    container_name: express-app
    ports:
      - "3002:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    # Add healthcheck to ensure express-app waits for redis
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:3000"]
      interval: 10s
      retries: 5
      start_period: 5s

volumes:
  redis-data: