
services:
  redis:
    image: ghcr.io/opes04/redis-image:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  bull-board:
    image: ghcr.io/opes04/bull-board-image:latest
    container_name: bull-board
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3001:3000"
    depends_on:
      - redis

  app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

volumes:
  redis-data:
